# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np

## Array related functions

In [2]:
a = np.array([5,6,7])
print(a[0])
print(a.ndim)
print(a.itemsize)
np.zeros( (2,3) )
np.ones( (2,3) )

5
1
8


array([[1., 1., 1.],
       [1., 1., 1.]])

## Array realted functions

In [3]:
a = np.array([[5,6,7],[8,9,10]], dtype=complex)
print(a[0])
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a)
print(a.size)
print(a.shape)


[5.+0.j 6.+0.j 7.+0.j]
2
16
complex128
[[ 5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j]]
6
(2, 3)


## Array creation


In [4]:
l = range(0, 5)
print(l)
l[0]

range(0, 5)


0

## Array creation or initialization

In [5]:
a = np.arange(1, 5)
print(a)
b = np.arange(1, 5, 2)
print(b)
c = np.linspace(1, 5, 10)
print(c)

[1 2 3 4]
[1 3]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


## Functions regarding shapes of array

In [6]:
a = np.array([[5,6,7],[8,9,10]])
print(a.ravel())
print(a.reshape(3, 2))

[ 5  6  7  8  9 10]
[[ 5  6]
 [ 7  8]
 [ 9 10]]


## Functions of array

In [7]:
a = np.array([[5,6,7],[8,9,10]])
print(a.min())
print(a.max())
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(np.sqrt(a))

5
10
45
[13 15 17]
[18 27]
[[2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766]]


## Arithmatic operation on array

In [8]:
a = np.array([[5,6,7],[8,9,10]])
b = np.array([[5,6,7],[8,9,10]])
print(a+b)
print(a*b)
print(a/b)
print(b.dot(a.T))

[[10 12 14]
 [16 18 20]]
[[ 25  36  49]
 [ 64  81 100]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[110 164]
 [164 245]]


## Array Indexing & Slicing

In [9]:
# Python List
n = [6, 7, 8]
n[0:2]

[6, 7]

In [10]:
# Numpy array
a = np.array([6, 7, 8])
a[0:2]

array([6, 7])

In [11]:
a[-1]

8

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
a[1,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6

In [13]:
# row 0 to 1 and col 2 will be printed
a[0:2, 2]

array([3, 6])

In [14]:
a[-1]

array([7, 8, 9])

In [15]:
a[-1, 0:2]

array([7, 8])

In [16]:
# more clear a[0:3, 1:2] and same
a[:, 1:2]

array([[2],
       [5],
       [8]])

## Iterating through numpy array

In [17]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [18]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


## Stacking two arrays

In [19]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [20]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

## Spliting array

In [22]:
a = np.arange(30).reshape(2, 15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [24]:
result = np.hsplit(a, 3)

In [25]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [26]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [27]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [28]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]